services:
  backend:
    build: ./backend
    container_name: family_calendar_backend
    ports:
      - "8000:8000"
    volumes:
      # Mount the data folder for your DB or other local storage
      - ./backend/data:/app/data
      # Mount credentials.json safely as read-only
      - ./backend/credentials.json:/app/core/credentials.json:ro
    restart: unless-stopped
    environment:
      # Pass Google creds path if needed in code
      GOOGLE_CREDS: /app/core/credentials.json

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://10.0.0.201:8000
    container_name: family_calendar_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

